### ISSUE TITLE
Allow snapshotter to update its own state to idle when it is halted

### ISSUE THREAD

**Issue by basz** [prooph/snapshotter#19]
When a snapshot script is halted it could finish a batch and set its own state to idle before it would halt the process.

// user land code
```
if (function_exists('pcntl_signal')) {
            pcntl_signal(SIGTERM, [$this, 'onPCNTLSignal']);
            pcntl_signal(SIGINT, [$this, 'onPCNTLSignal']);
}

public function onPCNTLSignal() {
        $this->projectionManager->stopProjection($this->snapshotStreamName);
}
```

To have this work the run [loop](https://github.com/prooph/pdo-event-store/blob/e5d8d610f908bb950433c4a2d600dcd6a36eef4b/src/Projection/PdoEventStoreReadModelProjection.php#L406-L452) must include `declare(ticks = 1);`.

**Comment by basz** [comment]
```
declare(ticks = 1);
```
 or 
```
if (function_exists('pcntl_signal')) {
    pcntl_signal_dispatch(); 
}
```
where `pcntl_signal_dispatch` is better; see comment http://stackoverflow.com/questions/31284051/understanding-php-declare-and-ticks

**Comment by prolic** [comment]
that's not needed, the status is still running but timed out. This can be
read in the event-store-ui f.e. and show the status "timed out" (calculated
by status: RUNNING + lock timeout is old)

Sascha-Oliver Prolic

2017-03-02 0:29 GMT+08:00 Bas Kamer <notifications@github.com>:

**Comment by basz** [comment]
isn't its dangerous to halt projections at any random point while it is executing a batch? What happens when it did handle the emitted event but not written its own state f.e.?

`pcntl_signal_dispatch` is not as expensive as declaring ticks and it does allow for clean shutdowns which are nice to have. a GUI is nice, but until then I'm looking at phpmyadmin...

**Comment by prolic** [comment]
You should not stop your running projection manually. If it crashes for whatever reasons and you cannot be sure about consistency anymore - restart your projection.
