### ISSUE TITLE
Update snapshot read model to allow reset() and delete()

### ISSUE THREAD

**Issue by prolic** [prooph/snapshotter#20]
see https://github.com/prooph/snapshotter/blob/develop/src/SnapshotReadModel.php

just call $snapshotStore->removeAll($aggregateType); in there. The constructor of the readmodel might need adjustments, so this value is present.

@basz maybe?

**Comment by basz** [comment]
Ok, tonight

**Comment by basz** [comment]
Q: How do I get to the AggregateType? The one that knows the type is obviously the repository but that's still a protected property. AggregateType::fromAggregateRepository could work if repository would implement AggregateTypeProvider?

other suggestions?

**Comment by prolic** [comment]
Inject in constructor?

Am 04.03.2017 02:55 schrieb "Bas Kamer" <notifications@github.com>:

**Comment by prolic** [comment]
Oh and please make the properties private instead of protected.

Am 04.03.2017 02:58 schrieb "Sascha-Oliver Prolic" <
saschaprolic@googlemail.com>:

**Comment by basz** [comment]
ok, that seems clear. except for this line https://github.com/prooph/snapshotter/blob/develop/src/SnapshotReadModel.php#L70 
A SnapshotReadModel might handle multiple types? No?...

**Comment by prolic** [comment]
No, it has not multiple types. Only multiple ar's per stream are handled
there. There is also only one repository injected.

Am 04.03.2017 03:11 schrieb "Bas Kamer" <notifications@github.com>:

**Comment by prolic** [comment]
Well, actually with inheritance you can have multiple types I think. So
let's inject an array of aggregate types. (User and admin both stored in
User repository f.e.)

Am 04.03.2017 03:15 schrieb "Sascha-Oliver Prolic" <
saschaprolic@googlemail.com>:
